stages:
  - test
  - build
  - deploy

test project:
  stage: test
  image: node:16
  script:
    - yarn
    - yarn test

build project:
  stage: build
  image: node:16
  script:
    - yarn
    - yarn build
  artifacts:
    paths:
      - build/

netlify:
  stage: deploy
  image: node:16
  script:
    - npm install -g netlify-cli
    - netlify deploy --dir=build --prod
